include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart

# All lints: https://dart-lang.github.io/linter/lints/
linter:
  rules:
    avoid_multiple_declarations_per_line: true
    use_named_constants: true
    # STYLE
    prefer_single_quotes: true
    cascade_invocations: true # May have issues: https://github.com/dart-lang/linter/issues/1589
    only_throw_errors: true
    prefer_foreach: true
    prefer_int_literals: true
    use_is_even_rather_than_modulo: true
    use_raw_strings: true

    # FLUTTER WEB IMPORTANT
    avoid_double_and_int_checks: true

    # DISABLE
    avoid_print: false
    prefer_const_constructors: false