name: StreaMap
description: A map displaying livestreams of zoos, concerts and other fun activities

version: 1.2.6

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  auto_size_text: 3.0.0-nullsafety.0
  cloud_firestore: 1.0.3
  cupertino_icons: 1.0.2

  firebase_analytics: 7.1.1
  firebase_core: 1.0.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: 0.4.0-nullsafety.3
  material_design_icons_flutter: 5.0.5955-rc.1
  package_info_plus: 1.0.0
  provider: 5.0.0
  rxdart: 0.26.0
  url_launcher: 6.0.3
  youtube_player_iframe: 2.0.0

dev_dependencies:
  effective_dart: 1.3.1
  flutter_launcher_icons: 0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/noun_Zebra_50798.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/noun_Zebra_50798_android.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
