name: StreaMap
description: A map displaying livestreams of zoos, concerts and other fun activities

version: 1.2.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: 0.14.0-dev.1
  firebase_analytics:
  firebase_core: 0.5.0-dev.1

  auto_size_text:
  cupertino_icons:
  flutter_staggered_grid_view:
  material_design_icons_flutter:
  provider:
  rxdart:
  url_launcher:
  youtube_player_iframe:

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart:
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/noun_Zebra_50798.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
